---
- name: Install MicroK8s on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: true
        state: present

    - name: Add user to microk8s group
      user:
        name: "sambath-nexn"
        groups: microk8s
        append: yes

    - name: Change ownership of the .kube directory
      file:
        path: /home/sambath-nexn/.kube
        state: directory
        owner: "sambath-nexn"
        group: "sambath-nexn"

    - name: Enable MicroK8s addons
      shell: |
        microk8s enable dns dashboard storage ingress
      args:
        executable: /bin/bash

    - name: Ensure MicroK8s is running
      shell: |
        microk8s status --wait-ready
      args:
        executable: /bin/bash

    - name: Configure kubectl alias
      shell: |
        snap alias microk8s.kubectl kubectl
      args:
        executable: /bin/bash

    - name: Ensure .kube config exists
      file:
        path: /home/sambath-nexn/.kube/config
        state: touch
        owner: "sambath-nexn"
        group: "sambath-nexn"

    - name: Set up kubeconfig for the user
      shell: |
        microk8s config > /home/sambath-nexn/.kube/config
      args:
        executable: /bin/bash
      become_user: "sambath-nexn"
