---
- name: Install MicroK8s on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: true
        state: present

    - name: Add user to microk8s group
      user:
        name: "<username>"
        groups: microk8s
        append: yes

    - name: Change ownership of the .kube directory
      file:
        path: /home/<username>/.kube
        state: directory
        owner: "<username>"
        group: "<username>"

    - name: Enable MicroK8s addons
      shell: |
        microk8s enable dns dashboard storage ingress
      args:
        executable: /bin/bash

    - name: Ensure MicroK8s is running
      shell: |
        microk8s status --wait-ready
      args:
        executable: /bin/bash

    - name: Configure kubectl alias
      shell: |
        snap alias microk8s.kubectl kubectl
      args:
        executable: /bin/bash

    - name: Ensure .kube config exists
      file:
        path: /home/<username>/.kube/config
        state: touch
        owner: "<username>"
        group: "<username>"

    - name: Set up kubeconfig for the user
      shell: |
        microk8s config > /home/<username>/.kube/config
      args:
        executable: /bin/bash
      become_user: "<username>"

    - name: Add the Open5GS Helm repository
      command: microk8s helm repo add adaptivenetlab https://adaptivenetlab.github.io/charts/

    - name: Update Helm repositories
      command: microk8s helm repo update

    - name: Open5gs Namespace
      command: microk8s kubectl create ns open5gs

    - name: Install Open5GS using Helm
      command: microk8s helm install my-open5gs adaptivenetlab/open5gs --version 1.0.3 -n open5gs

    - name: Check Open5gs NFV deployment
      command: microk8s kubectl get pod -n open5gs
