#---
#- name: Patch Kubernetes ConfigMap
#  hosts: localhost
#  gather_facts: no
#  tasks:
#    - name: Patch ConfigMap with new data
#      command: >
#        microk8s kubectl patch configmap my-open5gs-amf-config -n open5gs
#        --type merge
#        -p '{"plmn_id": {"mcc": "999", "mnc": "70", "tac": "1"}}'



---
- name: Apply Kubernetes ConfigMap Patch
  hosts: local
  gather_facts: no
  tasks:
    - name: Create configmap patch file
      copy:
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: my-open5gs-amf-config
            namespace: open5gs
          data:
            amf.yaml: |
              logger:
                  file: /var/log/open5gs/amf.log
              amf:
                  sbi:
                  - addr: 0.0.0.0
                    advertise: my-open5gs-amf
                  ngap:
                    dev: eth0
                  guami:
                      plmn_id:
                        mcc: 999
                        mnc: 70
                      amf_id:
                        region: 2
                        set: 1
                  tai:
                    - plmn_id:
                        mcc: 999
                        mnc: 70
                      tac: 1
                  plmn_support:
                  - plmn_id:
                      mcc: 999
                      mnc: 70
                    s_nssai:
                    - sst: 1
                      sd: ffffff
                  security:
                      integrity_order : [ NIA2, NIA1, NIA0 ]
                      ciphering_order : [ NEA0, NEA1, NEA2 ]
                  network_name:
                      full: Open5GS
                  amf_name: open5gs-amf0

              nrf:
               sbi:
                 name: my-open5gs-nrf

        dest: /tmp/configmap_patch.yml

    - name: Apply the patch to the ConfigMap
      command: microk8s kubectl apply -f /tmp/configmap_patch.yml

